# Spring properties
spring:
  application:
     name: facebook-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 6666   # HTTP (Tomcat) port

